export { default as AuctionDetailPage } from '@/pages/AuctionDetailPage/AuctionDetailPage';
export { default as AuctionPage } from '@/pages/AuctionPage/AuctionPage';
export { default as CreatePage } from '@/pages/CreatePage/CreatePage';
export { default as DepositPage } from '@/pages/DepositPage/DepositPage';
export { default as FundingPage } from '@/pages/FundingPage/FundingPage';
export { default as FundingPaymentPage } from '@/pages/FundingPaymentPage/FundingPaymentPage';
export { default as GalleryDetailPage } from '@/pages/GalleryDetailPage/GalleryDetailPage';
export { default as GalleryPage } from '@/pages/GalleryPage/GalleryPage';
export { default as ProfilePage } from '@/pages/ProfilePage/ProfilePage';
